// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVyaKHRJoh6Y72TidkyFB8Lqwstvm8-OU',
    appId: '1:918863544392:web:c10852a0d1851437a5587d',
    messagingSenderId: '918863544392',
    projectId: 'starter-template-a9308',
    authDomain: 'starter-template-a9308.firebaseapp.com',
    storageBucket: 'starter-template-a9308.appspot.com',
    measurementId: 'G-PJ089RVW5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_H1weKkfAuSS8HdgLFP010x7Yeh0rCU',
    appId: '1:918863544392:android:9faf4f7b15293971a5587d',
    messagingSenderId: '918863544392',
    projectId: 'starter-template-a9308',
    storageBucket: 'starter-template-a9308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQ-KyUML6cU6EKLy7PlC4-laD0p2lRG8',
    appId: '1:918863544392:ios:318585fdbb71cc64a5587d',
    messagingSenderId: '918863544392',
    projectId: 'starter-template-a9308',
    storageBucket: 'starter-template-a9308.appspot.com',
    iosClientId: '918863544392-ql1fbvhns2pnmm1m4ogn57i8vmnmee7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterResponsive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQ-KyUML6cU6EKLy7PlC4-laD0p2lRG8',
    appId: '1:918863544392:ios:318585fdbb71cc64a5587d',
    messagingSenderId: '918863544392',
    projectId: 'starter-template-a9308',
    storageBucket: 'starter-template-a9308.appspot.com',
    iosClientId: '918863544392-ql1fbvhns2pnmm1m4ogn57i8vmnmee7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterResponsive',
  );
}
